model: gbm_bestmodel
num_clients: 5
num_rounds: 20
random_seed: 42
oversampling: smote     # one of: smote, adasyn, none
smote_k_neighbors: 5
sampling_strategy: 0.01     # imblearn sampling_strategy; "auto"=1:1, e.g. 0.01 for 1:100
use_wandb: false
wandb_project: "fraud-fl-TA"
early_stop_patience: 10
partition:
  scheme: iid
  alpha: null
gbm_params:
  max_iter: 100
  learning_rate: 0.1
  max_depth: 6
